name: CI Pipeline

on:
  push:
    branches: [master]

jobs:
  build-and-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout app repo
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build & Push Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/gitops-app:${{ github.sha }} .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/gitops-app:${{ github.sha }}

      - name: Update image tag in gitops-config
        env:
          GH_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
        run: |
          git clone https://amrAdel-1:$GH_TOKEN@github.com/amrAdel-1/GitOps-config config-repo
          echo "=== BEFORE ===" && cat config-repo/apps/base/deployment.yaml | grep image
          sed -i "s|image: amradel2002/gitops-app:.*|image: ${{ secrets.DOCKERHUB_USERNAME }}/gitops-app:${{ github.sha }}|" config-repo/apps/base/deployment.yaml
          echo "=== AFTER ===" && cat config-repo/apps/base/deployment.yaml | grep image
          cd config-repo
          git remote set-url origin https://amrAdel-1:$GH_TOKEN@github.com/amrAdel-1/GitOps-config
          git config user.email "github-actions@github.com"
          git config user.name "GitHub Actions"
          git add .
          git commit -m "chore: update image tag to ${{ github.sha }}"
          git push origin master