on:
  push:
    branches: [master]

jobs:
  build-and-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout app repo
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login \
            -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build & Push Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/gitops-app:${{ github.sha }} .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/gitops-app:${{ github.sha }}

      - name: Update image tag in gitops-config
        run: |
          git clone https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ secrets.GITOPS_CONFIG_REPO }} gitops-config
          cd gitops-config

          sed -i "s|image: .*\/gitops-app:.*|image: ${{ secrets.DOCKERHUB_USERNAME }}/gitops-app:${{ github.sha }}|" \
            apps/base/deployment.yaml

          git config user.email "github-actions@github.com"
          git config user.name "GitHub Actions"
          git add .
          git commit -m "chore: update image tag to ${{ github.sha }}"
          git push